### ISSUE TITLE
[Question] autopep8 should be a development dependency?

### ISSUE THREAD

**Issue by onzalo** [MacHu-GWU/pathlib_mate-project#3]
**Is your feature request related to a problem? Please describe.**
We are using `uszipcode` which has `pathlib_mate` dependency and we are having dependency conflicts with autopep8.

Question: autopep8 is by mistake in requirements.txt? Shouldn't it be a development dependency?
Or am I missing something?

**Describe the solution you'd like**
Move autopep8 to requirements.dev.txt

**Comment by MacHu-GWU** [comment]
Yes you don't have use `autopep8` with `pathlib_mate`. It is an optional feature. I will remove that and add an alert.

**Comment by MacHu-GWU** [comment]
fixed in 1.1.1

**Comment by onzalo** [comment]
Thank you!
