### ISSUE TITLE
atomicwrites is deprecated

### ISSUE THREAD

**Issue by vectro** [MacHu-GWU/pathlib_mate-project#4]
The `atomicwrites` project is deprecated: https://github.com/untitaker/python-atomicwrites/tree/master

Maybe switch to `boltons` or `atomicfile`?

**Comment by MacHu-GWU** [comment]
@vectro  do you mean https://boltons.readthedocs.io/en/latest/fileutils.html#boltons.fileutils.atomic_save and https://pypi.org/project/atomicfile/

maybe bolton is a good idea. the second one is not actively in maintenance

**Comment by MacHu-GWU** [comment]
This is fixed in 1.3.1. However, now it requires python3.7+
